"""
Remote NPU training entry point.

Usage:
    # Dry-run: preview generated YAML without SSH
    python -m rllm_remote.train --dry-run

    # From CLI args
    python -m rllm_remote.train --lr 1e-6 --epochs 50 --batch-size 32

    # From JSON config (generated by rllm-config skill)
    python -m rllm_remote.train rllm_remote/output/runs/<run_id>/config.json
"""

import argparse
import os
import sys
from pathlib import Path


def main():
    parser = argparse.ArgumentParser(
        description="Launch remote NPU agent RL training on Huawei Ascend server",
    )

    # Connection
    parser.add_argument("--ssh-host", default="192.168.9.142")
    parser.add_argument("--ssh-port", type=int, default=22)
    parser.add_argument("--ssh-user", default="root")
    parser.add_argument("--ssh-key", default="~/.ssh/id_rsa")
    parser.add_argument("--ssh-password", default=None,
                       help="SSH password (uses sshpass -e, never logged)")
    parser.add_argument("--container", default="agent5.0.0_qjy")

    # Model / Data (server paths)
    parser.add_argument("--model-path", default=None)
    parser.add_argument("--train-data", default=None)
    parser.add_argument("--val-data", default=None)

    # Training
    parser.add_argument("--lr", type=float, default=1e-6)
    parser.add_argument("--batch-size", type=int, default=32)
    parser.add_argument("--mini-batch-size", type=int, default=8)
    parser.add_argument("--epochs", type=int, default=100)
    parser.add_argument("--num-samples", type=int, default=8)
    parser.add_argument("--kl-coef", type=float, default=0.001)
    parser.add_argument("--temperature", type=float, default=1.0)
    parser.add_argument("--max-prompt-len", type=int, default=2048)
    parser.add_argument("--max-response-len", type=int, default=2048)
    parser.add_argument("--entropy-coeff", type=float, default=0.0)

    # NPU / Cluster
    parser.add_argument("--tp-size", type=int, default=4)
    parser.add_argument("--pp-size", type=int, default=1)
    parser.add_argument("--num-npus", type=int, default=8)
    parser.add_argument("--gpu-mem-util", type=float, default=0.6)
    parser.add_argument("--train-engine", default="verl", choices=["verl", "megatron"])
    parser.add_argument("--cluster-mode", default="hybrid", choices=["hybrid", "one_step_off"])

    # Agent
    parser.add_argument("--agent-name", default="math")
    parser.add_argument("--max-agent-steps", type=int, default=5)
    parser.add_argument("--parallel-agents", type=int, default=1024)

    # Output
    parser.add_argument("--run-id", default="")
    parser.add_argument("--remote-output-dir", default="/home/work/AgentSDK/aura/outputs")
    parser.add_argument("--local-output-dir", default=None)

    # Misc
    parser.add_argument("--wandb-project", default="")
    parser.add_argument("--wandb-run", default="")
    parser.add_argument("--dry-run", action="store_true",
                       help="Generate and print YAML config without executing")
    parser.add_argument("--check", action="store_true",
                       help="Verify SSH connectivity and container status, then exit")
    parser.add_argument("config_json", nargs="?",
                        help="Path to RemoteTrainConfig JSON file (alternative to CLI args)")

    args = parser.parse_args()

    from rllm_remote.config import RemoteTrainConfig
    from rllm_remote.config_generator import generate_agentsdk_config

    # Build config from JSON or CLI args
    if args.config_json:
        config = RemoteTrainConfig.from_json(args.config_json)
        # CLI overrides for sensitive fields not in JSON
        if args.ssh_password:
            config.ssh_password = args.ssh_password
    else:
        kwargs = {}
        if args.model_path:
            kwargs["model_name_or_path"] = args.model_path
        if args.train_data:
            kwargs["train_data_path"] = args.train_data
        if args.val_data:
            kwargs["val_data_path"] = args.val_data
        if args.local_output_dir:
            kwargs["local_output_dir"] = args.local_output_dir
        if args.run_id:
            kwargs["run_id"] = args.run_id
        config = RemoteTrainConfig(
            ssh_host=args.ssh_host,
            ssh_port=args.ssh_port,
            ssh_user=args.ssh_user,
            ssh_key_path=args.ssh_key,
            ssh_password=args.ssh_password or "",
            container_name=args.container,
            lr=args.lr,
            train_batch_size=args.batch_size,
            ppo_mini_batch_size=args.mini_batch_size,
            num_epochs=args.epochs,
            n_samples_per_prompt=args.num_samples,
            kl_coef=args.kl_coef,
            temperature=args.temperature,
            max_prompt_length=args.max_prompt_len,
            max_response_length=args.max_response_len,
            entropy_coeff=args.entropy_coeff,
            tensor_parallel_size=args.tp_size,
            pipeline_parallel_size=args.pp_size,
            n_npus_per_node=args.num_npus,
            gpu_memory_utilization=args.gpu_mem_util,
            train_engine=args.train_engine,
            cluster_mode=args.cluster_mode,
            agent_name=args.agent_name,
            max_agent_steps=args.max_agent_steps,
            n_parallel_agents=args.parallel_agents,
            wandb_project=args.wandb_project,
            wandb_run_name=args.wandb_run,
            **kwargs,
        )

    # --dry-run: preview config and YAML
    if args.dry_run:
        print(config.summary())
        yaml_dict = generate_agentsdk_config(config)
        import yaml
        print("\n--- Generated AgentSDK YAML ---\n")
        print(yaml.dump(yaml_dict, default_flow_style=False, allow_unicode=True))
        return

    from rllm_remote.ssh import RemoteExecutor

    executor = RemoteExecutor(config)

    # --check: verify connectivity
    if args.check:
        print("Checking connectivity...")
        results = executor.verify_connectivity()
        for key, val in results.items():
            status = "OK" if val is True else "FAIL" if val is False else str(val)
            print(f"  {key}: {status}")
        all_ok = all(v is True for v in results.values())
        if not all_ok:
            sys.exit(1)
        print("All checks passed.")
        return

    # ---- Launch training ----

    print(config.summary())

    # 1. Verify container
    print("\n[1/4] Checking container...")
    if not executor.is_container_running():
        print(f"ERROR: Container '{config.container_name}' is not running on {config.ssh_host}")
        print("  Start it with: docker start agent5.0.0_qjy")
        sys.exit(1)
    print(f"  Container '{config.container_name}' is running.")

    # 2. Generate and upload YAML config
    print("[2/4] Generating and uploading AgentSDK config...")
    yaml_dict = generate_agentsdk_config(config)

    import yaml
    local_dir = os.path.join(config.local_output_dir, config.run_id)
    os.makedirs(local_dir, exist_ok=True)
    local_yaml = os.path.join(local_dir, "agentsdk_config.yaml")
    with open(local_yaml, "w") as f:
        yaml.dump(yaml_dict, f, default_flow_style=False, allow_unicode=True)

    # Save a local copy of RemoteTrainConfig for reference
    config.to_json(os.path.join(local_dir, "config.json"))

    # Config MUST be placed in AgentSDK's configs/ directory because:
    # 1. run_start_in_local.sh hardcodes --config-path to ${SCRIPT_DIR}/configs/
    # 2. Hydra searchpath (file://AgenticRL/configs/verl_conf) resolves
    #    relative to the config directory
    remote_configs_dir = f"{config.remote_agent_sdk_dir}/configs"
    remote_config_name = config.run_id
    remote_yaml_path = f"{remote_configs_dir}/{remote_config_name}.yaml"
    executor.run(f"mkdir -p {remote_configs_dir}")
    executor.upload_file(local_yaml, remote_yaml_path)
    print(f"  Config uploaded to: {remote_yaml_path}")
    print(f"  Local copy at:      {local_yaml}")

    # 3. Launch training via run_start_in_local.sh (handles PYTHONPATH, Ray, etc.)
    print("[3/4] Launching remote training in background...")
    log_file = f"{config.remote_output_dir}/{config.run_id}/training_log.txt"
    launch_cmd = f"bash run_start_in_local.sh --config-name {remote_config_name}"
    pid = executor.run_background(launch_cmd, log_file)
    # Save run_info for monitor auto-detection
    import json as _json
    with open(os.path.join(local_dir, "run_info.json"), "w") as _f:
        _json.dump({"pid": pid, "log_file": log_file}, _f)
    print(f"  PID:      {pid}")
    print(f"  Log file: {log_file}")

    # 4. Report
    print("\n[4/4] Training launched successfully!")
    print()
    print("=" * 60)
    print("Remote training is now running.")
    print()
    print(f"  Run ID:         {config.run_id}")
    print(f"  Server:         {config.ssh_user}@{config.ssh_host}:{config.ssh_port}")
    print(f"  Container:      {config.container_name}")
    print(f"  Remote config:  {remote_yaml_path}")
    print(f"  Remote log:     {log_file}")
    print(f"  PID:            {pid}")
    print()
    print("Monitor commands:")
    print(f"  SSH in:         ssh -p {config.ssh_port} {config.ssh_user}@{config.ssh_host}")
    print(f"  Tail log:       docker exec {config.container_name} tail -f {log_file}")
    print(f"  Check process:  docker exec {config.container_name} kill -0 {pid}")
    print(f"  Kill process:   docker exec {config.container_name} kill {pid}")
    print()
    print(f"  Local copy:     {local_dir}/")
    print("=" * 60)


if __name__ == "__main__":
    main()
